### ISSUE TITLE
Use models to gat age and gender

### ISSUE THREAD

**Issue by neumartin** [takuya-takeuchi/DlibDotNet#135]
Hi!

Can I use the models from https://github.com/justadudewhohacks/face-api.js?files=1 to detect gender and age?
Thanks!

**Comment by takuya-takeuchi** [comment]
@neumartin 
No. It looks like using TensorFlow. So dlib can not load this model file and DlibDotNet does not provide proper network to detect age and gender,

You may refer this repository to classify gender.
* https://github.com/cftang0827/face_gender
* https://github.com/davisking/dlib/issues/1227

And you can convert it to dlib network.
* https://github.com/spiorf/deepdream/blob/master/models/cnn_age_gender_models_and_data.0.0.2/deploy_age.prototxt

**Comment by takuya-takeuchi** [comment]
I trained UTKFace dataset and got train 99% and test 91% accuracy for gender classification.
I will be able to support gender classification on https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/feature/gender/examples/GenderTraining.
Not include it into DlibDotNet.

But I will NOT provide trained model file due to avoid license issue.
And it is too difficult to support age classification. I was not able to get even moderate accuracy.

**Comment by takuya-takeuchi** [comment]
Implemented age precition.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/develop/examples/AgeTraining

test accuracy is 0.76. But it is low accuracy. This function does not suit with production.
