### ISSUE TITLE
Unable to load DLL 'DlibDotNetNative'

### ISSUE THREAD

**Issue by tanhuynhhoang** [takuya-takeuchi/DlibDotNet#169]
# Summary of your issue
Exception thrown: 'System.DllNotFoundException' in DlibDotNet.dll
An unhandled exception of type 'System.DllNotFoundException' occurred in DlibDotNet.dll
Unable to load DLL 'DlibDotNetNative': Exception from HRESULT: 0xC000001D
# Environment
VS2017 x64, DlibDotNet 19.18.0.20191202
Write your environment.

# What did you do when you faced the problem?

HI!, i built app using DlibDotNet 19.18.0.20191202 for c#, although i had copied DlibDotNetNative.DLL same folder, it keep error
![Capture](https://user-images.githubusercontent.com/48179557/71627863-a9108400-2c27-11ea-80d5-94bfa5e76b69.PNG)

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
@tanhuynhhoang
I guess you did any configuration issue.
Could you give the following information to reproduce issue?

* .NET framework version (include .NET Core)
* Application Type (Console/WPF/WinForms)

And if you can, please upload minimum example project to reproduce this issue?
I think your code has no problem so I don't need only source code.

FYI
Just in case, could you check the following issue?
https://github.com/takuya-takeuchi/DlibDotNet/issues/168

**Comment by tanhuynhhoang** [comment]
thanks 
i just tested in windows console and windoem, same error issues
.Net framwork 4.6.1
`string file = "nguoila.jpg";
            using (var win = new ImageWindow())
            using (var detector = Dlib.GetFrontalFaceDetector())           
            using (var img = Dlib.LoadImage<byte>(file))
            {
                        Dlib.PyramidUp(img);

                        var dets = detector.Operator(img);
                        Console.WriteLine($"Number of faces detected: {dets.Length}");

                        win.ClearOverlay();
                        win.SetImage(img);
                        win.AddOverlay(dets, new RgbPixel { Red = 255 });

                        Console.WriteLine("hit enter to process next frame");
                        Console.ReadKey();
            }`

**Comment by takuya-takeuchi** [comment]
I created the example project includes the above code.
[#169.zip](https://github.com/takuya-takeuchi/DlibDotNet/files/4013783/169.zip)

But I was not able to reproduce issue.
So your env may have any issue.

Could you check the dependency of DlibDotNetNative.dll by using DependencyWalker?
You issue may indicate the lack of dependency libraries.

**Comment by tanhuynhhoang** [comment]
I had installed DependencyWalker, and foud that
![dependence](https://user-images.githubusercontent.com/48179557/71638146-9b401a80-2c8a-11ea-8b33-db6cec3fe81b.PNG)

**Comment by takuya-takeuchi** [comment]
Thanks a lot.

As far as I know, the bottom pain seem to be not useful.
This image indicates my machine information.

![image](https://user-images.githubusercontent.com/6241854/71647104-034b3b00-2d35-11ea-8d48-9f45239e42cb.png)

Basically, the first child node of DLIBDOTNETNATIVE.DLL should be checked.
Because, DlibDotNetNative does not depend on 3rd party library except for dlib.
But DlibDotNetNative links dlib as static library, so dlib is not present in this tree.
It means that there should not have any issue if first child node has no any error.

Therefore, I doubted and paid attention to the following points

* CPU issue. CPU is old? But error code is different.
  * https://github.com/takuya-takeuchi/DlibDotNet/issues/153
* VC Runtime issue. Requires VC++ 2017 runtime
  * But you had already installed it
* What is 0xC000001D? I have never seen this code in DllNotFoundException.
 * Google does not answer useful information.

BTW, did you launch your application directly?
Visual Studio may run application from directory which we does not intent to.

**Comment by tanhuynhhoang** [comment]
Thanks! 
i tried to code in new laptop using core i5 and Windows 10, it is OK!
So, i'am going to buy 1060 Ti Card for old PC, May I can use Dlibdotnet in GPU?

**Comment by takuya-takeuchi** [comment]
@tanhuynhhoang 
Good!!!

Yes, DlibDotNet support GPU.
You can use DlibDotNet.CUDAXXX nuget package. DlibDotNet nuget package does not link cuda library.
You can use GPU by only changing nuget package.

Have a try!!

**Comment by tanhuynhhoang** [comment]
Hi! takuya-takeuchi
I search all about your document but no place to show how to use function or syntax with cuda. Please show me!

**Comment by takuya-takeuchi** [comment]
@tanhuynhhoang 
No. There are no cuda syntax in dlib and DlibDotNet.
Cuda is used automatically if dlib links cuda library and system has gpu.
