### ISSUE TITLE
Runtime exceptions on server; works fine on local machine 

### ISSUE THREAD

**Issue by gabeking** [takuya-takeuchi/DlibDotNet#181]
# Summary of your issue

When trying to use any function in DlibDotNet 19.18.0.20200301 we encounter exceptions on the server. Everything behaves as expected in a local development environment. The exceptions are as follows:

```
The type initializer for 'DlibDotNet.NativeMethods' threw an exception.

Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

# Environment

Server:
Windows Server 2016, 64 bit
Intel Xeon E5

# What did you do when you faced the problem?

- ensured DLLs are present (in runtimes -> win-x64 -> native we have DlibDotNetNative.dll and DlibDotNetNativeDnn.dll)
DlibDotNet.dll is not present in this folder, but we tried copying it from bin -> x64 -> Debug -> netcoreapp3.1 where it is present with the same results
- tried specifying x64 build configuration in solution

the issue seems similar to https://stackoverflow.com/questions/58046780/facerecognitiondotnet-getting-error-unable-to-load-dll-dlibdotnetnative-or-o

I have read through some other similar issues on here but haven't had any luck with the proposed solutions yet. Please let me know if you have any advice! Thanks!

**Comment by Megadino** [comment]
@gabeking  the issue happens because the current version of DlibDotNet requires AVX instructions set be available in CPU, and Xeon has no AVX instructions. 

To run DlibDotNet  on Xeon or any other CPU without AVX instructions set, you need either to build DlibDotNet without AVX support by yourself, or use the older version of DlibDotNet which is non-AVX. 

Check #153  issue for details. Be aware that the latest available non-AVX version of DlibDotNet has bugs and may throw different exceptions that may be a blocker for your solution.

**Comment by gabeking** [comment]
@Megadino Thank you for your reply. We tried downgrading to version 19.17.0.20190813, and even further to version 19.17.0.20190623 and encountered the same exact problem. I can try building without AVX support, but the fact that these versions didn't work makes me suspicious that maybe there is another issue? Do you have any other suggestions or advice?

**Comment by takuya-takeuchi** [comment]
@Megadino 
Thank you for your kindly support!!

@gabeking 
I didn't find SO issue. Why didn't he report and check here? oh...

OK. your application can not load DlibDotNetNativeDnn.dll other than DlibDotNetNative.dll.
It guess AVX issues is gone and there is dependency issue.
Because windows show "Unable to load DLL 'DlibDotNetNative'" if AVX issue remains.
I think you deployed the application to WS2016 which has no developer tools, right?
If so, you machine requires VC++ Runtime.

![image](https://user-images.githubusercontent.com/6241854/79034530-a1328980-7bf1-11ea-8c65-cc65bf146522.png)

Dependency may let you notify the dependency issue.

Thanks.

**Comment by gabeking** [comment]
@takuya-takeuchi Thank you for your time and for the package! Installing the C++ runtime was necessary to even use the Dependencies tool, and ended up resolving the original issue too. I appreciate all the help!
