### ISSUE TITLE
How to load image from memory?

### ISSUE THREAD

**Issue by okolobaxa** [takuya-takeuchi/DlibDotNet#213]
Hello and thank you for this great library!

Here is my sample code to detect faces in the image. Can I somehow load the image not from disk but from memory?

```
[Fact]
        public async Task DlibTest()
        {
            using (var fd = Dlib.GetFrontalFaceDetector())
            {
                var img = Dlib.LoadImage<RgbPixel>("TestData/3.jpg");
                var faces = fd.Operator(img);
                Assert.NotEmpty(faces);
            }
        }
}
```

**Comment by Megadino** [comment]
@okolobaxa  if you want to load from memory, then you need to decode an image first. Dlib can load an image from memory, if you provide a byte array that contains a decoded image. The method itself is:

```
byte[] array; // this is an initialized array of pixels, and the  size of the image is 200x200 pixels, 3 bytes per pixel(RGB/BGR)
Dlib.LoadImageData<byte>(array, 200, 200, 200 * 3);

```
The tricky part here is how to get an image from JPGP/BMP/PBG/other file as a flat buffer(array) of pixels. There are many approaches to that. For instance - you can use .NET Bitmap class to load an image, then perform LockBits operation, get a pointer to raw data in memory, create a new byte array of needed size, pin the array to avoid garbage collection, copy to byte array and finally pass to Dlib.

Another approach with WPF BitmapSource class  - load an image, then allocate a byte array of appropriate size, pin it(GCHandle.Alloc(buffer, GCHandleType.Pinned);) , take a pointer and give to CopyPixels so it fills it with pixels data, then pass a byte array to DLib.

The third approach, if you use OpenCV - and have an image as Mat class, then it's pretty simple:
```
           Mat src; // this is OpenCV Mat image
            Array2D<byte> gray = null; // target Dlib array, it's grayscale, 1 byte per pixel
            int size = src.Width * src.Height * src.ElemSize();
            var array = pool.TakeBuffer(size); // I take an array from pool, but you can use also: var array = new byte[size];

            Marshal.Copy(src.Data, array, 0, size); // Copy pixels from Mat to the array

            //finally load data for Dlib from memory
            gray = Dlib.LoadImageData<byte>(array, (uint)src.Height, (uint)src.Width, (uint)(src.Width * src.ElemSize()));
```
@takuya-takeuchi  I think it really could be useful to have a method to load an image from a pointer IntPtr to avoid unnecessary memory allocations for byte[] (which is very inefficient in .NET). Because, we often load images with unmanaged code that provides a pointer to a flat pixel array, so this copying to byte[] looks excessive.

**Comment by takuya-takeuchi** [comment]
@Megadino 
Thank you for your kindly support.

> I think it really could be useful to have a method to load an image from a pointer IntPtr to avoid unnecessary memory allocations for byte[]

You meant that I will add the following method, right?

````csharp
public static Array2D<T> LoadImageData<T>(IntPtr pointer, uint rows, uint columns, uint steps)
````

If so, it couble be easy.
Because native method extensions_load_image_data2 accpets void* pointer.
So it does not need to modify native library.

**Comment by Megadino** [comment]
@takuya-takeuchi 
> You meant that I will add the following method, right?

That's right. If you add the method 
`public static Array2D<T> LoadImageData<T>(IntPtr pointer, uint rows, uint columns, uint steps)`
this will help a lot. 

Currently, for any image we want to pass to Dlib we need to allocate a managed memory in a heap, even if the memory is already allocated by unmanaged library that has decoded an image. By introducing a new method that takes IntPtr, we can decrease memory consumption twice, don't stress GC by huge memory allocations and get a performance boost as well. :)
