### ISSUE TITLE
Custom CNN_Face_detection

### ISSUE THREAD

**Issue by djthegr8** [takuya-takeuchi/DlibDotNet#233]
# Summary of your issue
There is no facility for a custom CNN to train, unlike python dlib.
## Example Code
```py
face_detector = dlib.cnn_face_detection_model_v1(path_to_detector)
```
## Why?
The current face detector fails when any sort of obstruction, say your hand, is placed before the face. This is not the case for other models, which is why I am asking for this.

**Comment by takuya-takeuchi** [comment]
@djthegr8 

cnn_face_detection_model_v1 is complex class for only python.  
cnn_face_detection_model_v1 is implemented by loss_mmod.
https://github.com/davisking/dlib/blob/f4f8bff95ec84d441953fb854c5261655c22c824/tools/python/src/cnn_face_detector.cpp#L127

So you can train face dataset by yourself.
Because net_type is already defined in 
https://github.com/takuya-takeuchi/DlibDotNet/blob/ba4c35f86c7e2495ec61db16f84d8521ace3e578/src/DlibDotNet.Native.Dnn/dlib/dnn/loss/mmod/defines.h#L22

Therefore your could use https://github.com/takuya-takeuchi/DlibDotNet/blob/master/examples/DnnMmodFaceDetection/Program.cs

**Comment by djthegr8** [comment]
Makes sense, thanks for the clarification.
