### ISSUE TITLE
DlibDotNet.UWP failed to build in Release mode - Microsoft.NetNative.targets(801,5): error : ILT0005:

### ISSUE THREAD

**Issue by goodmorningsky** [takuya-takeuchi/DlibDotNet#262]
# Summary of your issue
DlibDotNet.UWP failed to build in Release mode - Microsoft.NetNative.targets(801,5): error : ILT0005:
with UWP windows project without any code change. It just failed to compile in release mode as soon as it installs the Nudge Package "DlibDotNet.UWP". It works good in Debug model.

# Environment
Write your environment.
Windows 10, 
Microsoft Visual Studio Enterprise 2019 Version 16.6.1

# What did you do when you faced the problem? 
1. Open visual studio 2019
2. Create a new project : Blank App (Universal Windows) C# (by selecting category of C# > WIndows > UWP)
3. Leave version as is : Target version : Windows 10, version 20004, Minimum version: Windows 10, version 1809
    Compiled in Debug and Release modes => All works (It's just out of box project without any change)
4. Add Nudget package: DlibDotNet.UWP version 19.21.0.20210302 (The  latest available from search result)
5. NO Code change at all.
5. Build in Debug => Works GOOD.
6. Change build to "Release x64" => ERROR
1>    Generating code...
1>    Interop code generated.
1>  Compiling interop code
1>  Generating System.Reflection.DispatchProxy proxy code.
1>  Cleaning up unreferenced code
1>  Generating native code
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x64.microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\x64\ilc\Tools\nutc_driver.exe @"D:\Projects\TestProject\MyProjectTest\App3\obj\x64\Release\ilc\intermediate\MDIL\App3.rsp"' returned exit code -1073741819
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

7. Changed to "Release x86" => Same Error. 

//write here

## Example code:
No code change at all. Used the default UWP app from visual studio template
```
paste your core code
```

## Output:

```
paste your output
```

## What did you intend to be?
Every works fine in debug mode, but it doesn't compile at all as soon as changed it to Release mode.

Did I do wrong? I just compiled using the default "Build" button click in Visual Studio menu: Right click on the uwp project and click "Build" or "Rebuild" menu item.

Any comment helps.

**Comment by takuya-takeuchi** [comment]
It could be native tool chain issue but let me go through problem.

**Comment by goodmorningsky** [comment]
> It could be native tool chain issue but let me go through problem.

You are right. It's native tool chain issue. When I uncheck the "Compile with .NET Native tool chain", it works.
However, MS app store only accept the package compiled with Native tool chain, so it's important to make the compile works.

Looking forward your reply!

**Comment by takuya-takeuchi** [comment]
I couldn't dig out official reference from microsoft but some blogger says .NET Native restricts the following things

* usage of pointer array
* usage of more than 3 dimensional array
* usage of over 1mb struct

At least,  DlibDotNet violates the 1st rule.
But I'm not sure native build works or not after resoling it.

**Comment by goodmorningsky** [comment]
Thank you, Takuya for checking. I think integrating the library directly to UWP is not a good idea. The desktop bridge for UWP is a right solution in this case.
Thank you!

**Comment by valerysntx** [comment]
> I couldn't dig out official reference from microsoft but some blogger says .NET Native restricts the following things
> 

@takuya-takeuchi  [the-net-native-tool-chain](https://devblogs.microsoft.com/dotnet/the-net-native-tool-chain/#:~:text=The.NET%20Native%20tool-chain%20starts%20with%20the%20IL%20Compiler%2C,tools%20that%20generate%20code%20for%20marshaling%20and%20serialization.)

This issue is also related to the [runtime directives file ](https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/runtime-directives-rd-xml-configuration-file-reference) which is empty. 

Filling `serialization policies` for assemblies, namespaces, and types should help, while finding needed combination (if exists).

```
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
   <Application>
      <Assembly Name="DlibDotNet.UWP" Serialize="Required Public"
                Browse="All" Activate="PublicAndInternal"
                Dynamic="Public"  />
   </Application>
   <Library Name="UtilityLibrary">
     <!-- Child elements go here -->
   </Library>
</Directives>
```

Different [Dynamic](https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/runtime-directives-rd-xml-configuration-file-reference#the-effect-of-dynamic-policy) and [Serialize](https://docs.microsoft.com/en-us/windows/uwp/dotnet-native/runtime-directives-rd-xml-configuration-file-reference#the-effect-of-serialize-policy) property values should be set to build MDIL (ilc\intermediate\MDIL\App3.rsp)

Having policies:

- Activate. Controls runtime access to constructors, to enable activation of instances.

- Browse. Controls querying for information about program elements but does not enable any runtime access.

- Dynamic. Controls runtime access to all type members, including constructors, methods, fields, properties, and events, to enable dynamic programming.

- Serialize. Controls runtime access to constructors, fields, and properties, to enable type instances to be serialized and serialized by third-party libraries such as the Newtonsoft JSON serializer.

> Serialize policy enables the use of common reflection-based serializers. However, because the exact reflection access patterns of non-Microsoft serializers are not known to Microsoft, this policy may not be entirely effective.

...

So, while I agree that restrictions exists, 
> usage of pointer array
> usage of more than 3 dimensional array
> usage of over 1mb struct

We should agree that DlibDotNet is MDIL compatible or not for sure, so 
finding proper [rd.xml ](https://github.com/takuya-takeuchi/DlibDotNet/blob/8c1cbab8048e07fb74c6509401b68271a5f69bdf/examples/UWP/FaceDetection/Properties/Default.rd.xml) semantic could help

**Comment by valerysntx** [comment]
@takuya-takeuchi  Please reopen
