### ISSUE TITLE
How to call extract_image_4points functions in DlibDotNet

### ISSUE THREAD

**Issue by liuyang1921** [takuya-takeuchi/DlibDotNet#46]
# Summary of your issue
Hi, takuya,

      I am wondering if I could call the dlib function extract_image_4points  from DlibDotNet.
      It seemed that I could not find the function in the object browser of DlibDotNet, could 
 you give me some hint on how to achieve this goal?

        Thanks! 
# Environment

Write your environment.

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
I'm so sorry. I didn't implement it yet.
I implement function exists in sample project of dlib first.
Because sample projects let me know that own implementation is correct or not.

However, this function looks like to be easy to understand
So I added this function to 

* Matrix<T> Dlib.ExtractImage4Points<T>(Matrix<T>, DPoint[], int, int)
* Array2D<T> Dlib.ExtractImage4Points<T>(Array2D<T>, DPoint[], int, int)
  * Length of DPoint[] should be 4
  * int width and int height are output size you want

Please refer 221ce9688ad219aeea7542a898c8d0b57616db2d and build DlibDotNet and DlibDotNet.Native.

**Comment by liuyang1921** [comment]
Thank you, Takuya, I see! 

     Regards

**Comment by takuya-takeuchi** [comment]
It's my pleasure.
I always welcome request and questions :)
